CREATE TABLE sales (
    InventoryId VARCHAR(50),
    Store INTEGER,
    Brand INTEGER,
    Description TEXT,
    Size VARCHAR(50),
    SalesQuantity INTEGER,
    SalesDollars NUMERIC(12,2),
    SalesPrice NUMERIC(10,2),
    SalesDate DATE,
    Volume NUMERIC(10,2),
    Classification INTEGER,``
    ExciseTax NUMERIC(12,2),
    VendorNo INTEGER,
    VendorName VARCHAR(150)
);


SELECT COUNT(*) FROM sales;

---=====================================================Preview first 10 records

SELECT * FROM sales
LIMIT 10;




---=====================================================Total Sales Revenue

SELECT SUM(salesdollars) AS total_sales
FROM sales;


--===================================================== Total Quantity Sold

SELECT SUM(salesquantity) AS total_quantity
FROM sales;


---=====================================================Average Selling Price

SELECT ROUND(AVG(salesprice),2) AS average_price
FROM sales;


---=====================================================Number of Vendors


SELECT COUNT(DISTINCT vendorname) AS total_vendors
FROM sales;



--=====================================================Number of Brands


SELECT COUNT(DISTINCT brand) AS total_brands
FROM sales;



--=====================================================Number of Products


SELECT COUNT(DISTINCT description) AS total_products
FROM sales;



--=====================================================Total Revenue generated by each Vendor

SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY vendorname
ORDER BY total_sales DESC;


----===================================================== Total Quantity sold by each Vendor

SELECT vendorname, SUM(salesquantity) AS total_quantity
FROM sales
GROUP BY vendorname
ORDER BY total_quantity DESC;


----===================================================== Average Selling Price by Vendor


SELECT vendorname, ROUND(AVG(salesprice),2) AS average_price
FROM sales
GROUP BY vendorname
ORDER BY average_price DESC;



--=====================================================Unique Brands handled by each Vendor


SELECT vendorname, COUNT(DISTINCT brand) AS total_brands
FROM sales
GROUP BY vendorname
ORDER BY total_brands DESC;


--=====================================================Unique Products handled by each Vendor


SELECT vendorname, COUNT(DISTINCT description) AS total_products
FROM sales
GROUP BY vendorname
ORDER BY total_products DESC;


--=====================================================Revenue generated per unit sold


SELECT vendorname, ROUND(SUM(salesdollars)/SUM(salesquantity),2) AS revenue_per_unit
FROM sales
GROUP BY vendorname
ORDER BY revenue_per_unit DESC;



--====================================================Top 10 Vendors by Sales

SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY vendorname
ORDER BY total_sales DESC
LIMIT 10;


--=====================================================Bottom 10 Vendors by Sales

SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY vendorname
ORDER BY total_sales ASC
LIMIT 10;


--=====================================================Monthly Sales Trend


SELECT TO_CHAR(salesdate, 'month') AS month, 
ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY TO_CHAR(salesdate, 'month'),DATE_TRUNC('month', salesdate)
ORDER BY DATE_TRUNC('month', salesdate);


---=====================================================Monthly Quantity Trend

SELECT TO_CHAR(salesdate, 'month') AS month,
SUM(salesquantity) AS total_quantity
FROM sales
GROUP BY TO_CHAR(salesdate, 'month'), DATE_TRUNC('month', salesdate)
ORDER BY DATE_TRUNC('month', salesdate);



---====================================================Monthly Average Selling Price

SELECT TO_CHAR(salesdate, 'month') AS month,
ROUND(AVG(salesprice),2) AS average_price
FROM sales
GROUP BY TO_CHAR(salesdate, 'month'), DATE_TRUNC('month', salesdate)
ORDER BY DATE_TRUNC('month', salesdate);


-------------------////////////-------------------------VENDOR ANALYSIS




--==================================================== Top 10 Highest Revenue Products


SELECT description, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY description
ORDER BY total_sales DESC
LIMIT 10;



--====================================================Top 10 Highest Selling Products (Quantity)


SELECT description, SUM(salesquantity) AS total_quantity
FROM sales
GROUP BY description
ORDER BY total_quantity DESC
LIMIT 10;



--=====================================================Top 10 Brands by Revenue


SELECT brand, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY brand
ORDER BY total_sales DESC
LIMIT 10;

--=====================================================Store Wise Revenue


SELECT store, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY store
ORDER BY total_sales DESC;



---=====================================================Store Wise Quantity Sold


SELECT store, SUM(salesquantity) AS total_quantity
FROM sales
GROUP BY store
ORDER BY total_quantity DESC;


--=====================================================Vendor having Maximum Products


SELECT vendorname, COUNT(DISTINCT description) AS total_products
FROM sales
GROUP BY vendorname
ORDER BY total_products DESC;


--===================================================== Vendor having Maximum Brands


SELECT vendorname, COUNT(DISTINCT brand) AS total_brands
FROM sales
GROUP BY vendorname
ORDER BY total_brands DESC;



--=====================================================Average Revenue Per Transaction


SELECT vendorname, ROUND(AVG(salesdollars),2) AS average_transaction
FROM sales
GROUP BY vendorname
ORDER BY average_transaction DESC;

--=====================================================Vendors whose Sales are Above Average


WITH VendorSales AS (
    SELECT 
        vendorname,
        SUM(salesdollars) AS total_sales
    FROM sales
    GROUP BY vendorname
)
SELECT 
    vendorname,
    ROUND(total_sales, 2) AS total_sales
FROM VendorSales
WHERE total_sales > (SELECT AVG(total_sales) FROM VendorSales)
ORDER BY total_sales DESC;



---====================================================Vendors whose Sales are Below Average

WITH VendorSales AS (
    SELECT 
        vendorname,
        SUM(salesdollars) AS total_sales
    FROM sales
    GROUP BY vendorname
)
SELECT 
    vendorname,
    ROUND(total_sales, 2) AS total_sales
FROM VendorSales
WHERE total_sales < (SELECT AVG(total_sales) FROM VendorSales)
ORDER BY total_sales DESC;


---====================================================Revenue Contribution (%) of each Vendor


SELECT vendorname, ROUND(SUM(salesdollars) *100.0/ 
SUM(SUM(salesdollars)) OVER(),2) AS sales_contribution
FROM sales
GROUP BY vendorname
ORDER BY sales_contribution DESC;


---===================================================== Daily Sales Trend


SELECT salesdate, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY salesdate
ORDER BY salesdate;


--===================================================== Average Monthly Revenue


SELECT TO_CHAR(salesdate, 'month') AS month,
ROUND(AVG(salesdollars),2) AS average_sales
FROM sales
GROUP BY TO_CHAR(salesdate, 'month'), DATE_TRUNC('month', salesdate)
ORDER BY DATE_TRUNC('month', salesdate);


--===================================================== Vendor Performance Classification


SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales,
CASE
WHEN SUM(salesdollars)>=10000000 THEN 'High Performer'
WHEN SUM(salesdollars)>=5000000 THEN 'Medium Performer'
ELSE 'Low Performer'
END AS VendorCategory
FROM sales
GROUP BY vendorname
ORDER BY total_sales DESC;

--- =====================================================Top 10 Vendors Contribution in %age


SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales,
ROUND(SUM(salesdollars)*100.0/ (SELECT SUM(salesdollars) FROM sales),2) AS contribution_percent
FROM sales
GROUP BY vendorname
ORDER BY total_sales DESC
LIMIT 10;


---- =================================================== Highest Average Selling Price Vendor


SELECT vendorname, ROUND(AVG(salesprice),2) AS avg_price FROM sales
GROUP BY vendorname
ORDER BY avg_price DESC
LIMIT 10;


---- ===================================================== Top 5 Vendors using CTE


WITH VendorSales AS (
SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales
FROM sales
GROUP BY vendorname
)

SELECT * FROM VendorSales
ORDER BY total_sales DESC
LIMIT 5;

---- ===================================================== Rank Vendors based on Total Sales


SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales,
RANK() OVER(
ORDER BY SUM(salesdollars) DESC) AS sales_rank
FROM sales
GROUP BY vendorname;



--===================================================== Dense Rank Vendors based on Total Sales


SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales,
DENSE_RANK() OVER( ORDER BY SUM(salesdollars) DESC) AS sales_rank
FROM sales
GROUP BY vendorname;



---- =================================================== Assign Row Number to Vendors


SELECT vendorname, ROUND(SUM(salesdollars),2) AS total_sales,
ROW_NUMBER() OVER( ORDER BY SUM(salesdollars) DESC ) AS row_number
FROM sales
GROUP BY vendorname;

-- ===================================================== Running Total of Daily Sales


SELECT salesdate, ROUND(SUM(salesdollars),2) AS daily_sales,
ROUND(SUM(SUM(salesdollars))OVER( ORDER BY salesdate),2) AS running_total
FROM sales
GROUP BY salesdate
ORDER BY salesdate;


-- =====================================================Previous Day Sales using LAG()


SELECT salesdate, ROUND(SUM(salesdollars),2) AS daily_sales,
LAG(ROUND(SUM(salesdollars),2)) OVER (ORDER BY salesdate)
AS previous_day_sales
FROM sales
GROUP BY salesdate
ORDER BY salesdate;



-- ===================================================== Daily Growth compared to Previous Day


SELECT salesdate, ROUND(SUM(salesdollars),2) AS daily_sales,
ROUND(SUM(salesdollars) - LAG(SUM(salesdollars)) OVER(ORDER BY salesdate),2) AS growth
FROM sales
GROUP BY salesdate
ORDER BY salesdate;


--=====================================================Next Day Sales using LEAD()


SELECT salesdate, ROUND(SUM(salesdollars),2) AS daily_sales,
LEAD(ROUND(SUM(salesdollars),2)) OVER( ORDER BY salesdate ) AS next_day_sales
FROM sales
GROUP BY salesdate
ORDER BY salesdate;



---===================================================== 7-Day Moving Average of Daily Sales

SELECT salesdate, ROUND(SUM(salesdollars),2) AS daily_sales,
ROUND(AVG(SUM(salesdollars)) OVER(ORDER BY salesdate ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) AS moving_average
FROM sales
GROUP BY salesdate
ORDER BY salesdate;


---=====================================================Create Vendor Performance View

CREATE VIEW VendorPerformance AS
SELECT Vendorname, SUM(salesdollars) AS total_sales,
SUM(salesquantity) AS total_quantity,
AVG(salesprice) AS average_price
FROM sales
GROUP BY Vendorname;



---=====================================================Display Vendor Performance View

SELECT * FROM VendorPerformance
ORDER BY total_sales DESC;


----=====================================================Create Index on Vendor Name

CREATE INDEX idx_vendor
ON sales(vendorname);

---=====================================================Create Index on Sales Date

CREATE INDEX idx_salesdate
ON sales(salesdate);

--====================================================Analyze Query Performance using EXPLAIN ANALYZE

EXPLAIN ANALYZE
SELECT vendorname, SUM(salesdollars)
FROM sales
GROUP BY vendorname;